# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-21 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lyric',
            fields=[
                ('song_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('artists', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('locate_path', models.CharField(max_length=300)),
                ('last_modified', models.DateField(auto_now=True)),
            ],
        ),
    ]
