# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-22 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyric_exporter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lyric',
            name='id',
        ),
        migrations.AddField(
            model_name='lyric',
            name='file_name',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lyric',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lyric',
            name='song_id',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
